In [ ]:
import numpy as np
arr=np.arange(1, 10).reshape(3,3)
print(arr)
# shape,size,dimension
print("shape:",arr.shape)
print("size:",arr.size)
print("dimension:",arr.ndim)
print("2nd row:",arr[1])
print("third column:",arr[:,2])
print("center element:",arr[1][1])
print("multiply 2 with all elements:",arr*2)
print("sum of all elements:",arr.sum())
print("mean of all elements:",arr.mean())

In [3]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

# 1 d array

[1 2 3]


In [4]:
arr=np.array([[1,2,3],[1,2,3]])
print("2d array",arr)
print(arr.ndim)
print(arr.size)

2d array [[1 2 3]
 [1 2 3]]
2
6


In [5]:
d1=arr.flatten()

#covert 2d arrat into the 1d array


In [6]:
d1

array([1, 2, 3, 1, 2, 3])

In [ ]:
arr=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
print(arr)
print(arr.ndim)
print(arr.size)


#convert 3d into 2d
d3=arr.ravel()

d3

In [ ]:
#reshape
#convert 3d into 2d
import numpy as np
arr=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
arr=arr.reshape(3,3)
print(arr)
print(arr.ndim)
#2d array in find silice
arr[1,1]
print(arr.ndim)
print(arr.size)

In [ ]:
import numpy as np
arr=np.array([[[1,2,3],[1,2,3],[1,2,3]]])
#rr=arr.reshape()


s=arr.ravel()

s
#print(arr)
#print(arr.ndim)

In [ ]:
#multiple blocks
import numpy as np
arr=np.array([[[1,2,3],[1,3,4]],[[4,5,6],[7,8,9]],[[2,5,3],[9,0,2]]])
print(arr)

In [ ]:
#multiple blocks
import numpy as np
arr=np.array([[[1,2,3],[1,3,4]],[[4,5,6],[7,8,9]],[[2,5,3],[9,0,2]]])
print(arr)